# Generated by Django 2.1.1 on 2018-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitycredential',
            name='key_to_store',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
