# Generated by Django 2.1.2 on 2018-10-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_service', '0002_auto_20180731_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycredential',
            name='key_to_store',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
