# Generated by Django 4.1.1 on 2022-09-15 16:13

from django.db import migrations, models

import config_service.null_storage


class Migration(migrations.Migration):

    dependencies = [
        ("config_service", "0005_auto_20191125_1035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="securitycredential",
            name="key_to_store",
            field=models.FileField(
                blank=True,
                storage=config_service.null_storage.NullStorage(),
                upload_to="",
            ),
        ),
    ]
