# Generated by Django 4.1.1 on 2022-09-21 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config_service", "0006_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="integration_service",
        ),
    ]
