stages:
  - tests
  - build
  - deploy


complexity:
  stage: tests
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

tests:
  stage: tests
  script:
    - pipenv install --dev
    - export TESTING=true
    - pipenv run pytest --cov-report term-missing --cov=.

  services:

style:
  stage: tests
  script:
    - flake8

build-develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/europa:latest" .
    - docker push "$CI_REGISTRY/europa:latest"
  only:
    - develop

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/europa:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY/europa:$CI_COMMIT_TAG"
  only:
    - tags

deploy-dev:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: dev
  script:
    - bash collectstatic.sh
    - ENVIRONMENT=dev deploystatic
    - kubectl config use-context dev
    - kubectl delete po $(kubectl get po --no-headers=true -l run=europa -o custom-columns=:metadata.name)
  only:
    - develop

deploy-staging:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: staging
  script:
    - bash collectstatic.sh
    - ENVIRONMENT=staging deploystatic
    - kubectl config use-context staging
    - 'kubectl patch deployment/europa --patch "{\"spec\": {\"template\": {\"spec\": {\"initContainers\": [{\"name\": \"migrate\",\"image\": \"olympus.azurecr.io/europa:$CI_COMMIT_TAG\"}]}}}}"'
    - kubectl set image deployment/europa europa=olympus.azurecr.io/europa:$CI_COMMIT_TAG
  only:
    - tags

deploy-prod:
  stage: deploy
  image: binkops.azurecr.io/kubedeployer:latest
  environment: prod
  script:
    - bash collectstatic.sh
    - ENVIRONMENT=prod deploystatic
    - kubectl config use-context prod
    - 'kubectl patch deployment/europa --patch "{\"spec\": {\"template\": {\"spec\": {\"initContainers\": [{\"name\": \"migrate\",\"image\": \"olympus.azurecr.io/europa:$CI_COMMIT_TAG\"}]}}}}"'
    - kubectl set image deployment/hermes hermes=olympus.azurecr.io/europa:$CI_COMMIT_TAG
  when: manual
  only:
    - tags
